config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :messages
  resources :favorites, only: [:index, :create, :destroy]
  root to: "messages#index"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
belongs_to :user
belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
	mount_uploader :image, ImageUploader
	belongs_to :user
	validates :image,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :favorites, dependent: :destroy
	has_many :favorite_messages, through: :favorites, source: :message
	mount_uploader :picture, PictureUploader
	has_many :messages
	validates :name,  presence: true, length: { maximum: 30 }
	validates :email, presence: true, length: { maximum: 255 },
					  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
   before_validation { email.downcase! }
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def index
		@user = current_user
		@favorites = Favorite.where(user_id: @user.id).all
	end

	def create
		favorite = current_user.favorites.create(message_id: params[:message_id])
		redirect_to messages_url, notice: "#{favorite.message.user.name}さんのブログをお気に入り登録しました"
	end

	def destroy
		favorite = current_user.favorites.find_by(id: params[:id]).destroy
		redirect_to messages_url, notice: "#{favorite.message.user.name}さんのブログをお気に入り解除しました"
		
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :restrict_to_user, only: [:edit, :update, :destroy]
  def index
    @messages = Message.all
  end

  def show
    @favorite = current_user.favorites.find_by(message_id: @message.id)
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      MessageMailer.message_mail(@message).deliver
      redirect_to @message, notice: '投稿しました！'
    else
      render :new, notice: '投稿に失敗しました！'
    end

  end

  def update
    if current_user.id == @message.user_id
      if @message.update(message_params)
       redirect_to @message, notice: '投稿を更新しました！！' 
     else
      flash.now[:danger] = 'ユーザー情報の編集に失敗しました！！'
      render :edit
    end
    flash.now[:danger] = 'ユーザー情報の編集に失敗しました！！'
  end
end

def destroy
  @message.destroy
  redirect_to messages_url, notice: '投稿を削除しました！！' 
end

private

def restrict_to_user
  unless current_user == @message.user
    flash[:alert] = "あなたの投稿ではありません！"
    redirect_to root_path
  end
end

def set_message
  @message = Message.find(params[:id])
end

def message_params
  params.require(:message).permit(:content, :image, :image_cache)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_message, only: [:edit, :show, :update]

	def new
		@user = User.new
	end

	def edit
		
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to user_path(@user.id)
		else
			render 'new'
		end
	end

	def show
	end

	def update
		if current_user == @user
			if @user.update(user_params)
				flash[:success] = 'ユーザー情報を編集しました！'
				render :show
			else
				flash.now[:danger] = 'ユーザー情報の編集に失敗しました！！'
				render :edit
			end	
		else
			flash[:dender]= '他人のプロフィール情報は編集できません！'
			redirect_to  @user
		end
	end

	private

	def set_message
		@user = User.find(params[:id])
	end


	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1><%= @user.name %>さんの気に入り一覧</h1>
<div class="row">
	<% @favorites.each do |favorite| %>
	<div class="col-sm-6 col-md-4">
		<div class="thumbnail">
			<% message = Message.find(favorite.message_id) %>
			<%= image_tag message.image.url %>
			<div class="caption">
				<h4>投稿者</h4>
				<p><%=message.user.name%></p>
				<h4>内容</h4>
				<p><%=message.content%></p>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li class="active"><%=link_to "プロフィール", user_path(current_user.id)%></li>
        <li> <%=link_to "ログアウトする", session_path(current_user.id), method: :delete%></li>
        <li> <%=link_to "メッセージ一覧", messages_path %></li>
        <li><%= link_to "新規メッセージ", new_message_path%></li>
        <% else %>
        <li><%=link_to "新規アカウント登録", new_user_path, data: { turbolinks: false }%></li>
        <li><%=link_to "ログイン", new_session_path%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Costagramclone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/navigation'%>
  <div class="jumbotron">
    <h1>InstagramClone</h1>
  </div>
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/messages/_form.html.erb
<div class= 'row'>
  <div class = 'col-xs-12'>
    <%= form_with(model: message, local: true) do |form| %>
    <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class:"form-control" %>
    </div>

    <div class="field">
      <%= form.label :image %>
      <%= image_tag(@message.image.url) if @message.image && @message.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message, class:"btn btn-default"%> |
<%= link_to 'Back', messages_path, class:"btn btn-default" %>

app/views/messages/index.html.erb
<h1>Messages</h1>
<div class="row">
  <% @messages.each do |message| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag message.image_url %>
      <div class="caption">
        <h4>投稿者</h4>
        <p><%= message.user.name %></p>
        <h4>内容</h4>
        <p><%=message.content%></p>
        <p>
          <%= link_to 'Show', message, class:"btn btn-default" %>
          <% if message.user.id == current_user.id %>
          <%= link_to 'Edit', edit_message_path(message), class:"btn btn-default" %>
          <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default" %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @message.image.url %>
</p>

<% unless @message.user_id == current_user.id %>
<% if @favorite.present? %>
<%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
<%= link_to 'お気に入りする', favorites_path(message_id: @message.id), method: :post, class: 'btn btn-primary' %>
<% end %>
<% end %>
<% if @message.user.id == current_user.id %>
<%= link_to 'Edit', edit_message_path(@message), class:"btn btn-default" %>
<%= link_to 'Destroy', @message, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default" %>
<% end %>
<%= link_to 'Back', messages_path, class:"btn btn-default" %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-group">
  <%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :お名前 %>
  <%= f.text_field :name, required: true, placeholder: "Write your name" ,class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :メールアドレス %>
  <%= f.email_field :email, required: true, placeholder: "Write your email",class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :パスワード %>
  <%= f.password_field :password, required: true, placeholder: "Password",class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :確認用パスワード %>
  <%= f.password_field :password_confirmation, required: true, placeholder: "Password Confirmation",class: "form-control" %><br>
</div>
<div class="form-group">
  <%= f.label :picture %>
  <%= f.file_field :picture, required: true, placeholder: "Password Confirmation",class: "form-control" %><br>
</div>
<div class="actions">
  <%= f.submit "登録", class: "btn btn-default btn-sm" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザプロフィール編集</h1>
<%= render 'form'%>

<%= link_to 'Back', @user%>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページです</h1>
<h4>プロフィール画像</h4>
<P><%= image_tag @user.picture.url%></P>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to 'お気に入り一覧', favorites_path, class:"btn btn-default" %>

<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-default" %>